name: Docker CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Hadolint
        run: make lint
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.1
        with:
          version: v0.3.13
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      
      - name: Build the image
        run: |
          make build
          docker image ls
      
      - name: Test the image
        run: |
          docker image ls
          make test
